const DATA = [
    {
    id : 0,
    title : "Toyota Premio",
    manufacturer: "toyota",
    model : "XLE-Xse",
    price : "24,300",
    year : "2019",
    transmission : "Automatic",
    displacement: "1797cc",
    driveType : "FF",
    power: "158ps",
    TankCapacity : "60litres",
    consumption : "15km/l",
    mileage: "100,000km",
    img : "../images/premio2.jpg"
    },
    {
        id : 1,
        title : "Nissan Note",
        manufacturer: "nissan",
        model : "note",
        price : "12,580",
        year : "2019",
        transmission : "CVT",
        displacement: "1200cc",
        driveType : "FF",
        power: "79ps",
        TankCapacity : "41litres",
        consumption : "26mpg",
        img : "../images/note.jpg"
        },
    {
        id : 2,
        title : "Accord Honda",
        manufacturer : "Honda",
        model : "accord",
        price : "27,695",
        year : "2019",
        transmission : "6-Speed A/T",
        displacement: "1.5-liter 4cyl Turbo CVT",
        driveType : "FF",
        power: "192hp",
        TankCapacity : "50litres",
        consumption : "22mpg",
        mileage: "79,000km",
        img : "../images/accord.jpg"
    },
    {
        id : 3,
        title : "Toyota fielder",
        manufacturer : "toyota",
        model : "fielder",
        price : "30,695",
        year : "2019",
        transmission : "6-Speed A/T",
        displacement: "1.5-liter 4cyl Turbo CVT",
        driveType : "FF",
        power: "158hp",
        TankCapacity : "50litres",
        consumption : "14.4 km/l",
        img : "../images/fielder.jpg"
    },
    {
        id : 4,
        title : "Honda TypeR",
        manufacturer : "honda",
        model : "typeR",
        price : "40,695",
        year : "2019",
        transmission : "8-Speed Manual",
        displacement: "2.0-liter 4cyl Turbo",
        driveType : "FF",
        power: "192hp",
        TankCapacity : "47litres",
        consumption : "18mpg",
        mileage: "100,000km",
        img : "../images/typeR.jpg"
    },
    {
        id : 5,
        title : "Nissan Maxima",
        manufacturer : "nissan",
        model : "maxima",
        price : "33,695",
        year : "2019",
        transmission : "7-Speed A/T",
        displacement: "2.5-liter v6 Turbo CVT",
        driveType : "FF",
        power: "212hp",
        TankCapacity : "68litres",
        consumption : "17.7mg",
        mileage: "79,000km",
        img : "../images/maxima2017.jpg"
    },
    {
        id : 6,
        title : "Nissan March",
        manufacturer : "nissan",
        model : "march",
        price : "26,695",
        year : "2019",
        transmission : "7-Speed A/T",
        displacement: "1.3-liter v4 CVT",
        driveType : "FF",
        power: "68hp",
        TankCapacity : "29litres",
        consumption : "17.7mg",
        mileage: "79,000km",
        img : "../images/march.jpg"
    },
    {
        id : 7,
        title : "Suzuki Alto",
        manufacturer : "suzuki",
        model : "alto",
        price : "29,695",
        year : "2019",
        transmission : "6-Speed A/T",
        displacement: "1.0-liter",
        driveType : "FF",
        power: "68hp",
        TankCapacity : "29litres",
        consumption : "17.7mg",
        mileage: "79,000km",
        img : "../images/suzukialto.jpg"
    },
    {
        id : 8,
        title : "suzuki swift",
        manufacturer : "suzuki",
        model : "swift",
        price : "26,695",
        year : "2019",
        transmission : "7-Speed A/T",
        displacement: "1.5-liter v4 Turbo",
        driveType : "FF",
        power: "99hp",
        TankCapacity : "29litres",
        consumption : "17.7mg",
        mileage: "79,000km",
        img : "../images/swift.jpg"
    },
    {
        id : 9,
        title : "Mazda Axela",
        manufacturer : "mazda",
        model : "mazda 3",
        price : "26,695",
        year : "2019",
        transmission : "7-Speed A/T",
        displacement: "1.5-liter",
        driveType : "FF",
        power: "68hp",
        TankCapacity : "29litres",
        consumption : "17.7mg",
        mileage: "79,000km",
        img : "../images/axela.jpg"
    },
    {
        id : 10,
        title : "Toyota Probox",
        manufacturer : "toyota",
        model : "probox",
        price : "26,695",
        year : "2019",
        transmission : "7-Speed A/T",
        displacement: "1.5-liter ",
        driveType : "FF",
        power: "68hp",
        TankCapacity : "29litres",
        consumption : "17.7mg",
        mileage: "79,000km",
        img : "../images/probox.jpeg"
    },
    {
        id : 11,
        title : "Toyota Porte",
        manufacturer : "toyota",
        model : "porte",
        price : "26,695",
        year : "2019",
        transmission : "7-Speed A/T",
        displacement: "1.0-liter ",
        driveType : "FF",
        power: "45hp",
        TankCapacity : "20litres",
        consumption : "17.7mg",
        mileage: "108,000km",
        img : "../images/porte.jpg"
    }


]

export default DATA;